Update patch set 10
Patch Set 10: Code-Review-1

the linting of chart nonrtric failed.  In console log:
Error: found in requirements.yaml, but missing in charts/ directory: a1controller, a1simulator, controlpanel, policymanagementservice, nonrtric-common

Is the nonrtric chart (nonrtric/helm/nonrtric) necessary?  It appears to be an empty chart with only requirements.yaml calling for all other nonrtric charts.  Since the verify script does not really push those charts to local repo, this requirements will not be met.

Patch-set: 10
Reviewer: Gerrit User 1000001 <1000001@84e4e190-e623-4c37-9eda-58b1937c1b53>
Label: Code-Review=-1