Update patch set 23
Patch Set 23:

http://amd001.utah.cloudlab.us:32080/: SMO Build FAILED, TOX tests have crashed (http://amd001.utah.cloudlab.us:32080/job/gerrit-automatic-trigger-verify/job/64%252F7864%252F23/1/)

                process.kill()
                if _mswindows:
                    # Windows accumulates the output in a single blocking
                    # read() call run on child threads, with the timeout
                    # being done in a join() on those threads.  communicate()
                    # _after_ kill() is required to collect that and add it
                    # to the exception.
                    exc.stdout, exc.stderr = process.communicate()
                else:
                    # POSIX _communicate already populated the output so
                    # far into the TimeoutExpired exception.
                    process.wait()
                raise
            except:  # Including KeyboardInterrupt, communicate handled that.
                process.kill()
                # We don't call process.wait() as .__exit__ does that for us.
                raise
            retcode = process.poll()
            if check and retcode:
>               raise CalledProcessError(retcode, process.args,
                                         output=stdout, stderr=stderr)
E               subprocess.CalledProcessError: Command 'kubectl create namespace network' returned non-zero exit status 1.

/usr/lib/python3.8/subprocess.py:516: CalledProcessError
- generated xml file: /home/jenkins/agent/workspace/omatic-trigger-verify_64_7864_23/smo-install/test/pythonsdk/src/orantests/reports/junit/oran-tests.xml -
=========================== short test summary info ============================
ERROR src/orantests/test_apex_policy.py::test_apex_policy - waiting.exception...
ERROR src/orantests/test_o1.py::test_devices_in_sdnc - subprocess.CalledProce...
ERROR src/orantests/test_o1.py::test_device_faults_in_sdnc - subprocess.Calle...
ERROR src/orantests/test_o1.py::test_network_devices_registration_in_dmaap - ...
ERROR src/orantests/test_o1.py::test_device_faults_in_dmaap - subprocess.Call...
==================== 1 passed, 5 errors in 91.20s (0:01:31) ====================
/home/jenkins/agent/workspace/omatic-trigger-verify_64_7864_23/smo-install/test/pythonsdk/.tox/oran-tests/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.152.183.229'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
ERROR: InvocationError for command /home/jenkins/agent/workspace/omatic-trigger-verify_64_7864_23/smo-install/test/pythonsdk/.tox/oran-tests/bin/pytest -v --junit-xml=reports/junit/oran-tests.xml src/orantests/ (exited with code 1)
___________________________________ summary ____________________________________
  unit-tests: commands succeeded
  pylint: commands succeeded
  pydocstyle: commands succeeded
ERROR:   oran-tests: commands failed

Patch-set: 23
Tag: autogenerated:jenkins