Update patch set 4
Patch Set 4:

http://oran-smo-stable.oran.iol.unh.edu:32080/: SMO Build FAILED, TOX tests have crashed (http://oran-smo-stable.oran.iol.unh.edu:32080/job/gerrit-automatic-trigger-verify/job/17%252F8717%252F4/1/)

INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/.tox/oran-tests/lib/python3.8/site-packages/_pytest/main.py", line 267, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/.tox/oran-tests/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/.tox/oran-tests/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/.tox/oran-tests/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/.tox/oran-tests/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/.tox/oran-tests/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/src/orantests/conftest.py", line 102, in pytest_sessionstart
INTERNALERROR>     wait(lambda: policy_component_ready(), sleep_seconds=settings.POLICY_CHECK_RETRY, timeout_seconds=settings.POLICY_CHECK_TIMEOUT, waiting_for="Policy to be ready")
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/.tox/oran-tests/lib/python3.8/site-packages/waiting/__init__.py", line 18, in wait
INTERNALERROR>     for x in iterwait(result=result, *args, **kwargs):
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/.tox/oran-tests/lib/python3.8/site-packages/waiting/__init__.py", line 44, in iterwait
INTERNALERROR>     result.result = predicate()
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/src/orantests/conftest.py", line 102, in <lambda>
INTERNALERROR>     wait(lambda: policy_component_ready(), sleep_seconds=settings.POLICY_CHECK_RETRY, timeout_seconds=settings.POLICY_CHECK_TIMEOUT, waiting_for="Policy to be ready")
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/src/orantests/conftest.py", line 63, in policy_component_ready
INTERNALERROR>     policy_status = policy.get_components_status(settings.POLICY_BASICAUTH)
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/src/oransdk/policy/policy.py", line 60, in get_components_status
INTERNALERROR>     status = cls.send_message_json('GET',
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/.tox/oran-tests/lib/python3.8/site-packages/onapsdk/onap_service.py", line 238, in send_message_json
INTERNALERROR>     raise exception
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/.tox/oran-tests/lib/python3.8/site-packages/onapsdk/onap_service.py", line 222, in send_message_json
INTERNALERROR>     response = cls.send_message(method, action, url, **kwargs)
INTERNALERROR>   File "/home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/.tox/oran-tests/lib/python3.8/site-packages/onapsdk/onap_service.py", line 174, in send_message
INTERNALERROR>     raise ConnectionFailed(msg) from cause
INTERNALERROR> onapsdk.exceptions.ConnectionFailed: Can't connect to https://10.152.183.181:6969/policy/pap/v1/components/healthcheck.
ERROR: InvocationError for command /home/jenkins/agent/workspace/tomatic-trigger-verify_17_8717_4/smo-install/test/pythonsdk/.tox/oran-tests/bin/pytest -v --junit-xml=reports/junit/oran-tests.xml src/orantests/ (exited with code 3)
___________________________________ summary ____________________________________
  pylint: commands succeeded
  pydocstyle: commands succeeded
  unit-tests: commands succeeded
ERROR:   oran-tests: commands failed

Patch-set: 4
Tag: autogenerated:jenkins